name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_npm:
    if: ${{ github.repository == 'tediorelee/koishi-plugin-douyin' && !github.event.repository.fork }}
    permissions:
      id-token: write
      contents: read
    uses: koikirin/buildplate/.github/workflows/publish_npm.buildplate.yml@v1